In [30]:
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [31]:
salary = pd.read_csv('SalaryData.csv')

In [32]:
y = salary[['Salary']]

In [33]:
y

Salary
0    39343
1    42774
2    46205
3    37731
4    43525
5    39891
6    48266
7    56642
8    60150
9    54445
10   64445
11   60000
12   57189
13   60200
14   63218
15   55794
16   56957
17   57081
18   59095
19   61111
20   64500
21   67938
22   66029
23   83088
24   82200
25   81363
26   93940
27   91000
28   90000
29   91738
30   98273
31  101302
32  113812
33  111620
34  109431
35  105582
36  116969
37  112635
38  122391
39  121872

In [34]:
X = salary[['Experience Years']]

In [35]:
X

Experience Years
0                1.1
1                1.2
2                1.3
3                1.5
4                2.0
5                2.2
6                2.5
7                2.9
8                3.0
9                3.2
10               3.2
11               3.5
12               3.7
13               3.8
14               3.9
15               4.0
16               4.0
17               4.1
18               4.3
19               4.5
20               4.7
21               4.9
22               5.1
23               5.3
24               5.5
25               5.9
26               6.0
27               6.2
28               6.5
29               6.8
30               7.1
31               7.9
32               8.2
33               8.5
34               8.7
35               9.0
36               9.5
37               9.6
38              10.3
39              10.5

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

In [37]:
model = LinearRegression()

In [38]:
model.fit(X_train,y_train)

LinearRegression()

In [39]:
model.intercept_

array([26596.96131107])

In [40]:
model.coef_

array([[9405.61663234]])

In [41]:
a = np.array([10]).reshape(-1, 1)
model.predict(a)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[120653.12763442]])

In [42]:
y_pred = model.predict(X_test)

In [43]:
y_pred

array([[ 90555.15441095],
       [ 59516.61952424],
       [106544.70268592],
       [ 64219.42784041],
       [ 68922.23615658],
       [123474.81262412],
       [ 84911.78443155],
       [ 63278.86617718],
       [ 65159.98950364],
       [ 61397.74285071],
       [ 37883.70126987],
       [ 50111.00289191]])

In [46]:
px.scatter(x=X_train['Experience Years'], y=y_train['Salary'],template='seaborn')